## Car Detection

In [2]:
import cv2
import time
import numpy as np

# Create our body classifier
car_classifier = cv2.CascadeClassifier('D:/OpenCV_Projects-master/OpenCV_Projects-master/Sec05_Object_Detection_02/02_Car_Detection/cars.xml')

# Initiate video capture for video file
cap = cv2.VideoCapture('D:/OpenCV_Projects-master/OpenCV_Projects-master/Sec05_Object_Detection_02/02_Car_Detection/cars.avi')

# Loop once video is successfully loaded
while cap.isOpened():
    time.sleep(.05)
    # Read first frame
    _, frame = cap.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    # Pass frame to our car classifier
    cars = car_classifier.detectMultiScale(gray, 1.4, 2)
    print(cars)
    # Extract bounding boxes for any bodies identified
    for (x,y,w,h) in cars:
        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 255), 2)
        cv2.imshow('Cars', frame)
        #fourcc = cv2.VideoWriter_fourcc(*'MPEG')
        #out = cv2.VideoWriter('output.avi',fourcc, 20.0, (640,480))

    if cv2.waitKey(1) == 13: #13 is the Enter Key
        break

cap.release()
cv2.destroyAllWindows()

[[223  86  55  55]]
[[223  86  55  55]]
[[224  84  55  55]]
()
[[225  82  55  55]]
()
[[228  79  55  55]]
()
()
[[185  22  28  28]]
()
[[185  22  28  28]]
[[235  67  55  55]]
[[236  65  55  55]]
()
[[237  62  55  55]]
()
[[236  59  55  55]]
[[179  25  28  28]
 [238  59  55  55]]
[[238  56  55  55]]
()
[[241  53  55  55]]
[[239  53  55  55]
 [178  30  24  24]]
()
[[243  49  55  55]]
()
[[242  48  55  55]]
[[171  31  28  28]]
[[243  47  55  55]]
()
()
()
()
[[245  41  55  55]]
()
()
()
[[217 104  55  55]]
[[233  51  23  23]]
[[255  47  39  39]]
()
()
()
[[236  48  20  20]]
[[226  90  55  55]]
()
()
()
()
()
()
[[240  42  20  20]]
()
()
()
()
()
()
[[242  38  20  20]]
()
()
()
()
[[ 6 67 55 55]]
[[137  34  28  28]]
()
()
()
()
()
()
()
()
()
()
()
()
()
()
[[273  27  28  28]]
()
()
()
()
()
()
()
()
()
[[145 104  55  55]
 [221  85  55  55]]
[[146 103  55  55]
 [221  82  55  55]]
()
()
()
()
()
()
()
[[134 149  77  77]]
()
()
[[268  19  28  28]]
()
()
[[156 126  77  77]]
[[159 120  77  77]

- **Car Classifier ** - http://www.codeforge.com/read/241845/cars3.xml__html
